imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

doctrine:
    dbal:
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%db_test_name%"
        user:     "%database_user%"
        password: "%database_password%"

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
